create table if not exists public.transmissions (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  body text not null,
  tag text not null
);

alter table public.transmissions enable row level security;

drop policy if exists "transmissions are readable" on public.transmissions;

create policy "transmissions are readable"
  on public.transmissions
  for select
  to anon, authenticated
  using (true);

create index if not exists transmissions_created_at_idx
  on public.transmissions (created_at desc);

create index if not exists transmissions_tag_idx
  on public.transmissions (tag);
